# Sử dụng hình ảnh cơ sở ASP.NET Core runtime cho .NET 10
# docker build -t hano-base:latest -f ./dockerfiles/Dockerfile.base .

# docker save -o hano-base.tar hano-base:latest
# scp hano-base.tar user@host:/path/to/destination
# docker load -i hano-base.tar

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 80
